services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: accreditation_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - vendor_data:/var/www/html/vendor # named volume protects vendor
      - /var/www/html/storage/logs
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    container_name: accreditation_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  postgres:
    image: postgres:16
    container_name: accreditation_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: accreditation
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  node:
    image: node:22-alpine
    container_name: accreditation_node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"

volumes:
  pgdata:
  vendor_data:
