services:
  web:
    build:
      context: .
      dockerfile: ./docker/prod/nginx/Dockerfile
    restart: unless-stopped
    volumes:
      - storage-production:/var/www/storage:ro
      - public-assets:/var/www/public/build:ro
    networks:
      - production
    ports:
      - '8080:80'
    depends_on:
      php-fpm:
        condition: service_healthy  # Wait for php-fpm health check

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/prod/php-fpm/Dockerfile
      target: production
    restart: unless-stopped
    volumes:
      - public-assets:/var/www/public/build:rw  # Mount the public assets volume
      - storage-production:/var/www/storage  # Mount the storage volume
    env_file:
      - .env.production
    networks:
      - production
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    # The 'depends_on' attribute with 'condition: service_healthy' ensures that
    # this service will not start until the 'postgres' service passes its health check.
    # This prevents the application from trying to connect to the database before it's ready.
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17
    restart: unless-stopped
    user: postgres
    # ports:
    #   - '5432:5432'
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE:-pupcon}
      - POSTGRES_USER=${POSTGRES_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secret}
    volumes:
      - postgres-data-production:/var/lib/postgresql/data
    networks:
      - production
    # Health check for PostgreSQL
    # -----------------------------------------------------------
    # Health checks allow Docker to determine if a service is operational.
    # The 'pg_isready' command checks if PostgreSQL is ready to accept connections.
    # This prevents dependent services from starting before the database is ready.
    # -----------------------------------------------------------
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  production:

volumes:
  postgres-data-production:
  storage-production:
  public-assets:
