name: pupcon_production

services:
  database-production:
    image: postgres:18
    restart: unless-stopped
    ports:
      - "5432:5432" # optional; remove this if only containers need DB access
    volumes:
      - postgres-data-production:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE:-pupcon}
      POSTGRES_USER: ${POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pupcon_prod_network

  api-prod:
    image: ghcr.io/zero-index-developers/pupcon/pupcon-api:${APP_VERSION}
    container_name: pupcon-api-prod
    restart: unless-stopped
    depends_on:
      database-production:
        condition: service_healthy
    env_file:
      - ./.env.production
    environment:
      - XDG_CONFIG_HOME=/tmp/.config
      - HOME=/tmp
    volumes:
      - laravel-storage-production:/var/www/storage
    networks:
        - pupcon_prod_network

  web-prod:
    image: ghcr.io/zero-index-developers/pupcon/pupcon-client:${APP_VERSION}
    container_name: pupcon-client-prod
    restart: unless-stopped
    depends_on:
      - api-prod
    volumes:
      - laravel-storage-production:/var/www/storage:ro
    ports:
      - "80:80"
    networks:
      - pupcon_prod_network

volumes:
  postgres-data-production:
  laravel-storage-production:

networks:
  pupcon_prod_network:
    driver: bridge
